options.md
jedahan/geometry pull request #9
Opened 2019-02-16 12:17 UTC by MarioRicalde

A draft with what you can set to customize, also ensuring that the one-liners that are fetched from the file are properly written. 

- [ ] Draft.
- [ ] Document all variables. 
- [ ] Previews.

2019-02-16 12:23 UTC, MarioRicalde commented
@jedahan @justmendes can you guys double check to make sure I'm not missing any variable?

Also, I'm thinking once we have this file we need to copy it and just add the older variable equivalents, and then we can do the automation and the updating guide. 

Thoughts?

2019-02-17 23:14 UTC, jedahan commented
My main suggestion is to find a formatting that makes it a bit easier to scan - all the backticks visually feel cramped. Perhaps using tables, especially for git, perhaps something like:

##  [geometry_git.zsh](functions/geometry_git.zsh)

|`geometry_git_stashes()`|  |
|:-----------------------|--------|
|GEOMETRY_GIT_COLOR_STASHES | 144|
|GEOMETRY_GIT_SYMBOL_STASHES | ●|

|`geometry_git_time()`|  |
|:-----------------------|--------|
GEOMETRY_COLOR_NO_TIME | white
GEOMETRY_GIT_NO_COMMITS_MESSAGE | no-commits 
GEOMETRY_GIT_TIME_DETAILED|false

2019-02-17 23:43 UTC, MarioRicalde commented
Most definitely, I'm going to be adding proper formatting to this document. What you see at the moment is just a list of variables, definitely not ready.

Is there anything in there that you notice I'm missing? If not, I can get to finishing this today.

2019-02-18 11:09 UTC, justmendes commented
Nice work!

Some minor things: can we put this into a `docs` directory? Also, can you add a title (e.g `# Customization Options`) and a small intro paragraph explaining how to do that (adding to zshrc, before sourcing geometry, etc)?

2019-02-18 20:05 UTC, jedahan requested changes
There are a decent number of inline GEOMETRY_ env options, not all are defined with `: ${GEOMETRY_THING...` syntax.

2019-02-18 20:05 UTC, jedahan commented on options.md
> +`GEOMETRY_VIRUALENV_CONDA_COLOR` - `DEFAULT_COLOR`
now both of these are simply 'green' and easier to override

2019-02-18 20:05 UTC, jedahan commented on options.md
> +### `geometry_rustup.zsh`
there is GEOMETRY_RUSTUP_PIN can be set to keep rustup rendering even out of context

`also GEOMETRY_RUSTUP_SYMBOL:=⚙`

2019-02-18 20:05 UTC, jedahan commented on options.md
> +### `geometry_node.zsh`
GEOMETRY_NODE_PIN can be set to always show geometry_node, even outside the context of a node project folder

2019-02-18 20:05 UTC, jedahan commented on options.md
> +### `geometry_kube.zsh`
GEOMETRY_KUBE_PIN as below

2019-02-18 20:05 UTC, jedahan commented on options.md
> +### `geometry_git.zsh`
GEOMETRY_GIT_GREP (though its in conflicts, I think it should be top level) can be used to override our searching for rg > ag > grep

2019-02-18 20:05 UTC, jedahan commented on options.md
> +Options: none.
`${GEOMETRY_DOCKER_MACHINE_COLOR:=blue} "(${GEOMETRY_DOCKER_MACHINE_SYMBOL:="⚓"}`

2019-02-18 20:07 UTC, MarioRicalde commented on options.md
> +`GEOMETRY_VIRUALENV_CONDA_COLOR` - `DEFAULT_COLOR`
Great job. I was wondering what was the reasoning behind keeping it like that!

2019-02-18 20:36 UTC, jedahan commented on options.md
> +``GEOMETRY_RUSTUP_SYMBOL` - ⚙
accidental double backtick?

2019-02-18 20:39 UTC, MarioRicalde commented
@jedahan I added the variables you suggested. 👍 

@justmendes I've pushed the introduction.

I'm still pending formatting.

2019-02-19 05:09 UTC, jedahan commented on options.md
> +Configuring Geometry is just a matter of setting some variables **before** sourcing the theme itself. Below, you'll find a list of all possible options that you can set that will override Geometry ap
So I think you don't need to set the variables before anymore. Most functions read the variables in live. If you find any that don't, we should file bugs.

2019-02-19 06:08 UTC, MarioRicalde commented on options.md
> +Configuring Geometry is just a matter of setting some variables **before** sourcing the theme itself. Below, you'll find a list of all possible options that you can set that will override Geometry ap
That's good to know, updating.

2019-02-19 06:10 UTC, MarioRicalde commented on options.md
> +``GEOMETRY_RUSTUP_SYMBOL` - ⚙
Yep, resolving. I'll work on formatting next.

2019-02-21 10:21 UTC, MarioRicalde commented
I've added some table formatting to the document; however, there's still several that are pending documentation in the description.

One thing that I'm thinking on doing is taking screenshots of the prompts to go hand in hand with these tables, but maybe down the line.

2019-02-21 10:48 UTC, MarioRicalde commented
@jedahan I've added descriptions to the best of my ability - but I'm sure I'm missing something. Also, the table of contents is there. Could you please review and advise if there's anything that needs to change.

Thank you.

2019-02-21 14:45 UTC, jedahan approved these changes
Minor nitpick, but I am happy to merge this in, thanks for all the hard work!

2019-02-21 14:45 UTC, jedahan commented on options.md
> +      - [Options](#options)
I would remove the options ToC link for everything - even with git we can just have it like follows:
```markdown
- [`geometry_git.zsh`](#geometrygitzsh)
  - [`geometry_git_stashes()`](#geometrygitstashes)
```

2019-02-21 14:45 UTC, jedahan commented on options.md
> +      - [Options](#options)
Actually how about removing the `####options` subheader from all sections as it feels redundant?

2019-02-21 14:47 UTC, merged